# Generated by Django 4.1.3 on 2022-12-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(max_length=180, null='True', upload_to='images/'),
            preserve_default='True',
        ),
    ]
