# Generated by Django 4.1.3 on 2022-12-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
        ('news', '0005_alter_newsstory_image_url'),
    ]

    operations = [
    ]
