# Generated by Django 4.1.3 on 2022-12-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_merge_20221211_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='image',
        ),
    ]
