# Generated by Django 4.1.3 on 2022-12-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
